# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: jhipstersampleapplication001
services:
  app:
    image: jhipstersampleapplication001
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://mssql:1433;database=jhipsterSampleApplication001;encrypt=false
      - SPRING_LIQUIBASE_URL=jdbc:sqlserver://mssql:1433;database=jhipsterSampleApplication001;encrypt=false
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8081/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      mssql:
        condition: service_healthy
  mssql:
    extends:
      file: ./mssql.yml
      service: mssql
  consul:
    extends:
      file: ./consul.yml
      service: consul
  consul-config-loader:
    extends:
      file: ./consul.yml
      service: consul-config-loader
